/**
 * home 模板几何定义（数据驱动版）—— 从定型脚本 replicate-home.js 逐版块提取。
 * 只含几何（bbox/槽位/尺寸）+ 配色键 + 内容键 content；不含任何俄语文案。
 * 坐标均为"版块内偏移"（相对版块顶部 oy），渲染时加 oy。
 * 颜色值存键名，渲染时从 colors 取（cardSub/summaryBody 为补充字面色键）。
 */
const colors = {
  navy: "#05284e",
  navyDeep: "#082848",
  inkBlock: "#1b222a",
  bannerGray: "#586878",
  grayTag: "#5c6876",
  whiteCard: "#f1f5f8",
  funcBg: "#e9f0f7",
  ink: "#16233b",
  inkSoft: "#33405c",
  muted: "#66708a",
  line: "#d7dee8",
  zebra: "#eef3f8",
  white: "#ffffff",
  bg: "#f4f8fc",
  cardSub: "#cdd9e8",
  summaryBody: "#e8eef5",
};

const sections = [
  // 1. 首页（顶部深蓝细条 + 品牌行/大标题/副题 + 大图 + 三统计卡）
  {
    type: "homeHero",
    content: "hero",
    height: 981,
    g: {
      topBar: { x: 0, y: 0, w: 900, h: 21, color: "navy" },
      brandLine: {
        x: 60,
        y: 66,
        w: 500,
        h: 30,
        role: "body",
        weight: "bold",
        color: "grayTag",
        align: "left",
        cap: { max: 22, min: 14 },
      },
      title: {
        x: 60,
        y: 120,
        w: 780,
        h: 60,
        role: "display",
        weight: "black",
        color: "ink",
        align: "left",
        cap: { max: 46, min: 30 },
      },
      sub: {
        x: 60,
        y: 190,
        w: 780,
        h: 30,
        role: "body",
        weight: "regular",
        color: "muted",
        align: "left",
        cap: { max: 22, min: 15 },
      },
      photo: { x: 60, y: 245, w: 780, h: 470, r: 14 },
      cards: {
        x0: 60,
        y: 744,
        cardW: 225,
        cardH: 120,
        gap: 30,
        r: 10,
        color: "navy",
        num: {
          yOff: 28,
          role: "display",
          weight: "extrabold",
          color: "white",
          align: "center",
          h: 44,
          cap: { max: 34, min: 22 },
        },
        label: {
          yOff: 78,
          role: "body",
          weight: "regular",
          color: "cardSub",
          align: "center",
          h: 28,
          cap: { max: 19, min: 13 },
        },
      },
    },
  },
  // 2. 产品梗概（整版蓝灰底 + 深蓝标签胶囊 + 白字标题/正文）
  {
    type: "homeSummary",
    content: "summary",
    height: 150,
    g: {
      bg: { x: 0, y: 0, w: 900, h: 150, color: "bannerGray" },
      tag: {
        x: 60,
        y: 20,
        w: 168,
        h: 26,
        r: 5,
        color: "navy",
        tx: 74,
        ty: 24,
        tw: 150,
        th: 22,
        cap: { max: 17, min: 12 },
      },
      title: {
        x: 60,
        y: 60,
        w: 780,
        h: 30,
        role: "display",
        weight: "bold",
        color: "white",
        align: "left",
        cap: { max: 26, min: 17 },
      },
      body: {
        x: 60,
        y: 98,
        w: 780,
        h: 40,
        role: "body",
        weight: "regular",
        color: "summaryBody",
        align: "left",
        cap: { max: 21, min: 15, factor: 1.3 },
      },
    },
  },
  // 3. 核心功能（浅蓝底 + 标题/副题 + 左大图 + 右三行：胶囊+标题+描述）
  {
    type: "homeFeatures",
    content: "features",
    height: 746,
    g: {
      bg: { x: 0, y: 0, w: 900, h: 746, color: "funcBg" },
      title: {
        x: 60,
        y: 24,
        w: 400,
        h: 40,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 30, min: 20 },
      },
      sub: {
        x: 60,
        y: 70,
        w: 500,
        h: 26,
        role: "body",
        weight: "regular",
        color: "muted",
        align: "left",
        cap: { max: 20, min: 14 },
      },
      photo: { x: 60, y: 130, w: 320, h: 560, r: 12 },
      rows: {
        x: 447,
        ys: [147, 360, 575],
        chip: {
          w: 123,
          h: 30,
          r: 5,
          color: "navy",
          textY: 6,
          textW: 123,
          textH: 24,
          cap: { max: 16, min: 11 },
        },
        head: {
          x: 447,
          yOff: 48,
          w: 393,
          h: 32,
          role: "display",
          weight: "bold",
          color: "ink",
          align: "left",
          cap: { max: 25, min: 17 },
        },
        desc: {
          x: 447,
          yOff: 88,
          w: 393,
          h: 70,
          role: "body",
          weight: "regular",
          color: "inkSoft",
          align: "left",
          cap: { max: 19, min: 14, factor: 1.35 },
        },
      },
    },
  },
  // 4. 细节描述（标题 + 两组纵排：图 + 标题 + 描述）
  {
    type: "homeDetailRows",
    content: "detail",
    height: 772,
    g: {
      title: {
        x: 60,
        y: 20,
        w: 400,
        h: 40,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 30, min: 20 },
      },
      rows: {
        x: 60,
        w: 300,
        photoH: 260,
        photoR: 12,
        ys: [120, 440],
        textX: 400,
        textW: 440,
        head: {
          yOff: 40,
          h: 36,
          role: "display",
          weight: "bold",
          color: "ink",
          align: "left",
          cap: { max: 26, min: 18 },
        },
        desc: {
          yOff: 100,
          h: 120,
          role: "body",
          weight: "regular",
          color: "inkSoft",
          align: "left",
          cap: { max: 21, min: 15, factor: 1.4 },
        },
      },
    },
  },
  // 5. 场景展示（深蓝整版底 + 标题/副题 + 2×2 白卡场景图）
  {
    type: "homeSceneGrid",
    content: "scene",
    height: 981,
    g: {
      bg: { x: 0, y: 0, w: 900, h: 981, color: "navyDeep" },
      title: {
        x: 60,
        y: 60,
        w: 400,
        h: 40,
        role: "display",
        weight: "extrabold",
        color: "white",
        align: "left",
        cap: { max: 32, min: 22 },
      },
      sub: {
        x: 60,
        y: 112,
        w: 700,
        h: 26,
        role: "body",
        weight: "regular",
        color: "cardSub",
        align: "left",
        cap: { max: 20, min: 14 },
      },
      cols: [60, 465],
      rowYs: [222, 546],
      cardW: 366,
      cardH: 279,
      cardR: 10,
      cardColor: "whiteCard",
      imgPadBottom: 34,
      photoR: 10,
      capOff: 249,
      cap: {
        w: 366,
        h: 24,
        role: "body",
        weight: "semibold",
        color: "navy",
        align: "center",
        cap: { max: 17, min: 12 },
      },
    },
  },
  // 6. 产品参数表（白底 + 标题/副题 + 无面板斑马两列）
  {
    type: "homeParamTable",
    content: "params",
    height: 792,
    g: {
      title: {
        x: 60,
        y: 20,
        w: 400,
        h: 42,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 30, min: 20 },
      },
      sub: {
        x: 60,
        y: 70,
        w: 500,
        h: 24,
        role: "body",
        weight: "regular",
        color: "muted",
        align: "left",
        cap: { max: 19, min: 14 },
      },
      top: 150,
      rowH: 72,
      zebra: { x: 60, yOff: -8, w: 780, color: "zebra" },
      key: {
        x: 86,
        yOff: 14,
        w: 320,
        h: 30,
        role: "body",
        weight: "bold",
        color: "navy",
        align: "left",
        cap: { max: 22, min: 15 },
      },
      val: {
        x: 430,
        yOff: 14,
        w: 400,
        h: 30,
        role: "body",
        weight: "regular",
        color: "inkSoft",
        align: "left",
        cap: { max: 22, min: 15 },
      },
    },
  },
  // 7. 产品使用教程（标题/副题 + 3 步序号圆 + 底部分隔线）
  {
    type: "homeSteps",
    content: "steps",
    height: 674,
    g: {
      title: {
        x: 60,
        y: 20,
        w: 500,
        h: 42,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 30, min: 20 },
      },
      sub: {
        x: 60,
        y: 70,
        w: 500,
        h: 24,
        role: "body",
        weight: "regular",
        color: "muted",
        align: "left",
        cap: { max: 19, min: 14 },
      },
      ys: [150, 340, 530],
      circle: { x: 90, yOff: 24, r: 30, color: "navy" },
      num: {
        x: 60,
        yOff: 2,
        w: 60,
        h: 44,
        role: "num",
        weight: "bold",
        color: "white",
        align: "center",
        cap: { max: 30, min: 20 },
      },
      head: {
        x: 150,
        yOff: 0,
        w: 400,
        h: 32,
        role: "display",
        weight: "bold",
        color: "ink",
        align: "left",
        cap: { max: 24, min: 17 },
      },
      desc: {
        x: 150,
        yOff: 44,
        w: 660,
        h: 40,
        role: "body",
        weight: "regular",
        color: "inkSoft",
        align: "left",
        cap: { max: 20, min: 14, factor: 1.3 },
      },
      line: { x1: 60, x2: 840, y: 480, w: 2, color: "line" },
    },
  },
  // 8. 品牌故事（大标题 + 三段正文 + 横图 + 底部深蓝圆角横幅）
  {
    type: "homeBrandStory",
    content: "brand",
    height: 641,
    tailPad: 20,
    g: {
      title: {
        x: 60,
        y: 60,
        w: 780,
        h: 44,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 30, min: 20 },
      },
      body: {
        x: 60,
        y: 150,
        pitch: 44,
        w: 780,
        h: 30,
        role: "body",
        weight: "regular",
        color: "inkSoft",
        align: "left",
        cap: { max: 22, min: 16 },
      },
      photo: { x: 60, y: 350, w: 780, h: 135, r: 10 },
      banner: {
        x: 60,
        y: 501,
        w: 780,
        h: 90,
        r: 10,
        color: "navy",
        titleX: 60,
        titleY: 525,
        titleW: 200,
        titleH: 40,
        titleColor: "white",
        titleCap: { max: 32, min: 22 },
        lineX: 260,
        lineY: 535,
        lineW: 560,
        lineH: 30,
        lineColor: "cardSub",
        lineCap: { max: 20, min: 14 },
      },
    },
  },
];

module.exports = {
  key: "home",
  width: 900,
  topPad: 30,
  gap: 34,
  colors,
  sections,
};
