/**
 * garden 模板几何定义（数据驱动版）—— 从定型脚本 replicate-garden.js 逐版块提取。
 * 只含几何（bbox/槽位/尺寸）+ 配色键 + 内容键 content；不含任何俄语文案。
 * 坐标均为"版块内偏移"（相对版块顶部 oy），渲染时加 oy。
 * 颜色值存键名，渲染时从 colors 取（cardFrame/bannerLine 为补充字面色）。
 */
const colors = {
  titleDark: "#164e36",
  titleMid: "#2e7d4f",
  icon: "#2e7d4f",
  panelParam: "#e1eae1",
  panelCompare: "#719483",
  frameBeige: "#ece6d7",
  chipGreen: "#d5e7c5",
  chipBeige: "#e6d2b8",
  accent: "#77b83f",
  bannerGG: "#687868",
  textBg: "#e8f8e8",
  line: "#cdd9cf",
  ink: "#1c381c",
  inkSoft: "#33453a",
  muted: "#5c6b60",
  white: "#ffffff",
  bg: "#f8f8f8",
  cardFrame: "#8fb39e",
  bannerLine: "#eef2ee",
};

const sections = [
  // 1. 概述
  {
    type: "overview",
    content: "overview",
    height: 188,
    g: {
      tag: {
        x: 78,
        y: 30,
        w: 231,
        h: 38,
        r: 6,
        color: "titleDark",
        tx: 98,
        ty: 36,
        tw: 200,
        th: 30,
        cap: { max: 22, min: 14 },
      },
      title: {
        x: 78,
        y: 86,
        w: 744,
        h: 44,
        role: "display",
        weight: "black",
        color: "ink",
        align: "left",
        cap: { max: 34, min: 22 },
      },
      sub: {
        x: 78,
        y: 140,
        w: 720,
        h: 26,
        role: "body",
        weight: "regular",
        color: "muted",
        align: "left",
        cap: { max: 20, min: 14 },
      },
    },
  },
  // 2. 首页（满幅场景大图 + 居中标题描述）
  {
    type: "heroPhoto",
    content: "hero",
    height: 987,
    g: {
      tag: {
        x: 78,
        y: 27,
        w: 255,
        h: 36,
        r: 6,
        color: "titleMid",
        tx: 98,
        ty: 33,
        tw: 220,
        th: 30,
        cap: { max: 22, min: 14 },
      },
      photo: { x: 78, y: 80, w: 744, h: 560, r: 14 },
      title: {
        x: 78,
        y: 665,
        w: 744,
        h: 44,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "center",
        cap: { max: 32, min: 22 },
      },
      desc: {
        x: 78,
        y: 725,
        w: 744,
        h: 150,
        role: "body",
        weight: "regular",
        color: "inkSoft",
        align: "center",
        cap: { max: 23, min: 17, factor: 1.4 },
      },
    },
  },
  // 3. 文字描述（浅绿整版底）
  {
    type: "textBlock",
    content: "description",
    height: 304,
    g: {
      bg: { x: 0, y: 0, w: 900, h: 304, color: "textBg" },
      tag: {
        x: 78,
        y: 48,
        w: 99,
        h: 30,
        r: 6,
        color: "titleMid",
        tx: 98,
        ty: 52,
        tw: 90,
        th: 26,
        cap: { max: 20, min: 12 },
      },
      body: {
        x: 78,
        y: 100,
        w: 744,
        h: 160,
        role: "body",
        weight: "regular",
        color: "ink",
        align: "left",
        cap: { max: 24, min: 17, factor: 1.4 },
      },
    },
  },
  // 4. 卖点详情（图标方块 + 3 行）
  {
    type: "bullets",
    content: "bullets",
    height: 781,
    g: {
      tag: {
        x: 78,
        y: 30,
        w: 216,
        h: 36,
        r: 6,
        color: "titleDark",
        tx: 98,
        ty: 36,
        tw: 190,
        th: 30,
        cap: { max: 22, min: 14 },
      },
      title: {
        x: 78,
        y: 92,
        w: 560,
        h: 34,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 27, min: 18 },
      },
      itemYs: [183, 375, 567],
      icon: {
        x: 96,
        w: 54,
        h: 51,
        r: 8,
        color: "icon",
        checkX: 123,
        checkOff: 26,
        checkR: 20,
      },
      head: {
        x: 172,
        offY: 4,
        w: 664,
        h: 30,
        role: "display",
        weight: "bold",
        color: "ink",
        align: "left",
        cap: { max: 25, min: 16 },
      },
      desc: {
        x: 172,
        offY: 40,
        w: 664,
        h: 30,
        role: "body",
        weight: "regular",
        color: "inkSoft",
        align: "left",
        cap: { max: 21, min: 15, factor: 1.25 },
      },
    },
  },
  // 5. 细节图文（左竖线 + 左大图 + 右 3 组）
  {
    type: "detailSplit",
    content: "detail",
    height: 886,
    g: {
      vline: { x: 48, y: 21, w: 3, h: 843, color: "line" },
      tag: {
        x: 78,
        y: 30,
        w: 270,
        h: 36,
        r: 6,
        color: "titleMid",
        tx: 98,
        ty: 36,
        tw: 240,
        th: 30,
        cap: { max: 21, min: 13 },
      },
      title: {
        x: 78,
        y: 92,
        w: 444,
        h: 34,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 27, min: 18 },
      },
      photo: { x: 75, y: 150, w: 447, h: 672, r: 12 },
      textX: 556,
      textW: 268,
      groupH: [170, 380, 560],
      groupD: [240, 450, 630],
      dHeights: [110, 90, 90],
      head: {
        role: "body",
        weight: "semibold",
        color: "ink",
        align: "left",
        h: 60,
        cap: { max: 22, min: 15, factor: 1.2 },
      },
      desc: {
        role: "body",
        weight: "regular",
        color: "inkSoft",
        align: "left",
        cap: { max: 19, min: 14, factor: 1.35 },
      },
    },
  },
  // 6. 场景展示（2×2 图网格 + caption）
  {
    type: "photoGrid",
    content: "scene",
    height: 826,
    g: {
      tag: {
        x: 78,
        y: 27,
        w: 198,
        h: 36,
        r: 6,
        color: "titleDark",
        tx: 98,
        ty: 33,
        tw: 170,
        th: 30,
        cap: { max: 22, min: 14 },
      },
      title: {
        x: 78,
        y: 93,
        w: 600,
        h: 34,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 27, min: 18 },
      },
      cols: [78, 470],
      colW: 354,
      imgH: 270,
      rowYs: [130, 470],
      photoR: 10,
      capOff: 282,
      cap: {
        role: "body",
        weight: "semibold",
        color: "inkSoft",
        align: "center",
        w: 354,
        h: 30,
        cap: { max: 19, min: 13, factor: 1.15 },
      },
    },
  },
  // 7. 参数表（浅绿面板 + 斑马两列）
  {
    type: "paramTable",
    content: "params",
    height: 726,
    g: {
      tag: {
        x: 78,
        y: 30,
        w: 180,
        h: 36,
        r: 6,
        color: "titleMid",
        tx: 98,
        ty: 36,
        tw: 160,
        th: 30,
        cap: { max: 20, min: 13 },
      },
      title: {
        x: 78,
        y: 92,
        w: 400,
        h: 32,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 26, min: 17 },
      },
      panel: { x: 78, y: 144, w: 747, h: 534, r: 10, color: "panelParam" },
      rowTopOff: 6,
      rowAreaH: 522,
      zebra: { x: 84, w: 735, color: "white" },
      key: {
        x: 104,
        offY: 20,
        w: 300,
        h: 34,
        role: "body",
        weight: "bold",
        color: "titleDark",
        align: "left",
        cap: { max: 23, min: 15 },
      },
      val: {
        x: 440,
        offY: 20,
        w: 360,
        h: 34,
        role: "body",
        weight: "regular",
        color: "muted",
        align: "left",
        cap: { max: 23, min: 15 },
      },
    },
  },
  // 8. 安装使用（2×2 卡片）
  {
    type: "stepCards",
    content: "install",
    height: 636,
    g: {
      tag: {
        x: 78,
        y: 30,
        w: 198,
        h: 36,
        r: 6,
        color: "titleDark",
        tx: 98,
        ty: 36,
        tw: 200,
        th: 28,
        cap: { max: 19, min: 12 },
      },
      title: {
        x: 78,
        y: 93,
        w: 600,
        h: 32,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 26, min: 17 },
      },
      grid: {
        x0: 78,
        y0: 150,
        cardW: 360,
        cardH: 205,
        gapX: 24,
        gapY: 24,
        cols: 2,
      },
      frame: {
        r: 14,
        color: "cardFrame",
        inset: 3,
        innerR: 12,
        innerColor: "white",
      },
      num: {
        cxOff: 46,
        cyOff: 52,
        r: 28,
        color: "titleDark",
        txOff: 18,
        tyOff: 30,
        tw: 56,
        th: 44,
        cap: { max: 32, min: 20 },
      },
      head: {
        xOff: 88,
        yOff: 32,
        wOff: 110,
        h: 40,
        role: "display",
        weight: "bold",
        color: "ink",
        align: "left",
        cap: { max: 24, min: 15 },
      },
      desc: {
        xOff: 24,
        yOff: 100,
        wOff: 48,
        h: 90,
        role: "body",
        weight: "regular",
        color: "inkSoft",
        align: "left",
        cap: { max: 19, min: 14, factor: 1.35 },
      },
    },
  },
  // 9. 竞品对比（深绿表头三列 + 斑马行）
  {
    type: "compareTable",
    content: "compare",
    height: 706,
    g: {
      tag: {
        x: 78,
        y: 30,
        w: 216,
        h: 36,
        r: 6,
        color: "titleDark",
        tx: 98,
        ty: 36,
        tw: 180,
        th: 30,
        cap: { max: 22, min: 14 },
      },
      title: {
        x: 78,
        y: 91,
        w: 600,
        h: 32,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "left",
        cap: { max: 26, min: 17 },
      },
      container: { x: 75, y: 150, w: 750, h: 483, r: 10, color: "panelParam" },
      head: {
        yOff: 3,
        h: 66,
        r: 6,
        color: "titleDark",
        textOffY: 21,
        textH: 30,
        cells: [
          {
            x: 96,
            w: 190,
            align: "left",
            color: "white",
            cap: { max: 21, min: 14 },
          },
          {
            x: 294,
            w: 255,
            align: "center",
            color: "white",
            cap: { max: 22, min: 15 },
          },
          {
            x: 552,
            w: 270,
            align: "center",
            color: "white",
            cap: { max: 22, min: 15 },
          },
        ],
      },
      body: {
        topOff: 69,
        padBottom: 6,
        zebra: { x: 81, w: 738, color: "white" },
        textOffY: 22,
        textH: 30,
        cols: [
          {
            x: 96,
            w: 190,
            weight: "bold",
            color: "titleDark",
            align: "left",
            cap: { max: 20, min: 13 },
          },
          {
            x: 294,
            w: 255,
            weight: "bold",
            color: "titleMid",
            align: "center",
            cap: { max: 21, min: 14 },
          },
          {
            x: 552,
            w: 270,
            weight: "regular",
            color: "muted",
            align: "center",
            cap: { max: 21, min: 14 },
          },
        ],
      },
    },
  },
  // 10. 品牌故事（满幅大图 + 居中文案 + 灰绿横幅）
  {
    type: "brandStory",
    content: "brand",
    height: 977,
    g: {
      tag: {
        x: 78,
        y: 27,
        w: 288,
        h: 36,
        r: 6,
        color: "titleDark",
        tx: 98,
        ty: 33,
        tw: 250,
        th: 30,
        cap: { max: 21, min: 13 },
      },
      photo: { x: 78, y: 80, w: 744, h: 420, r: 14 },
      title: {
        x: 78,
        y: 530,
        w: 744,
        h: 36,
        role: "display",
        weight: "extrabold",
        color: "ink",
        align: "center",
        cap: { max: 28, min: 18 },
      },
      body: {
        x: 78,
        y: 585,
        w: 744,
        h: 120,
        role: "body",
        weight: "regular",
        color: "inkSoft",
        align: "center",
        cap: { max: 21, min: 15, factor: 1.45 },
      },
      service: {
        x: 78,
        y: 712,
        w: 744,
        h: 28,
        role: "body",
        weight: "bold",
        color: "titleMid",
        align: "center",
        cap: { max: 22, min: 15 },
      },
      contentH: 770,
      banner: {
        y: 770,
        h: 187,
        color: "bannerGG",
        titleX: 78,
        titleYOff: 40,
        titleW: 400,
        titleH: 40,
        titleColor: "white",
        titleCap: { max: 34, min: 22 },
        lineX: 78,
        lineYOff: 92,
        linePitch: 30,
        lineW: 760,
        lineH: 26,
        lineColor: "bannerLine",
        lineCap: { max: 22, min: 15 },
      },
      tailPad: 20,
    },
  },
];

module.exports = {
  key: "garden",
  width: 900,
  topPad: 40,
  gap: 34,
  colors,
  sections,
};
